server:
  port: 8000


spring:
 
#  profiles:
#    active: test
 
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:verizon_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:April@2304}
  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        
   
